
name: matryoshka_top_300_dict_65536
# optimization parameters
seed: 49
batch_size: 4096
lr: 0.003
l1_coeff: 0
beta1: 0.9
beta2: 0.99
max_grad_norm: 100000
num_epochs: 2
wandb_name: "sae_matryoshka_top_300"
train_cache_size: 8000000
val_data_size: 1000000

# model parameters
sae_type: matryoshka_sae
dtype: torch.bfloat16
model_dtype: torch.bfloat16
n_batches_to_dead: 20
act_size: 4096
top_k: 300
top_k_aux: 512
aux_penalty: 0.03125
input_unit_norm: false
group_sizes: [1024, 1024, 2048, 4096, 8192, 16384, 32768]
dict_size: 65536

# training setup
dataset_path: ${SAEDIT_DATASET_PATH:-./data/embeddings.zarr}
results_path: ${SAEDIT_RESULTS_PATH:-./results}

perf_log_freq: 100
checkpoint_freq: 10000
data_loader_workers: 1

bandwidth: 0.001