name: saedit_env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.2
  - pthread-stubs=0.3
  - python=3.9.23
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
    - accelerate==1.10.1
    - asciitree==0.3.3
    - certifi==2025.10.5
    - charset-normalizer==3.4.3
    - diffusers==0.35.1
    - fasteners==0.20
    - filelock==3.19.1
    - fsspec==2025.9.0
    - hf-xet==1.1.10
    - huggingface-hub==0.35.3
    - idna==3.11
    - importlib-metadata==8.7.0
    - jinja2==3.1.6
    - markupsafe==3.0.3
    - mpmath==1.3.0
    - networkx==3.2.1
    - numcodecs==0.12.1
    - numpy==2.0.2
    - nvidia-cublas-cu12==12.8.4.1
    - nvidia-cuda-cupti-cu12==12.8.90
    - nvidia-cuda-nvrtc-cu12==12.8.93
    - nvidia-cuda-runtime-cu12==12.8.90
    - nvidia-cudnn-cu12==9.10.2.21
    - nvidia-cufft-cu12==11.3.3.83
    - nvidia-cufile-cu12==1.13.1.3
    - nvidia-curand-cu12==10.3.9.90
    - nvidia-cusolver-cu12==11.7.3.90
    - nvidia-cusparse-cu12==12.5.8.93
    - nvidia-cusparselt-cu12==0.7.1
    - nvidia-nccl-cu12==2.27.3
    - nvidia-nvjitlink-cu12==12.8.93
    - nvidia-nvtx-cu12==12.8.90
    - packaging==25.0
    - pandas==2.3.3
    - pillow==11.3.0
    - psutil==7.1.0
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - pyyaml==6.0.3
    - regex==2025.9.18
    - requests==2.32.5
    - safetensors==0.6.2
    - sentencepiece==0.2.1
    - six==1.17.0
    - sympy==1.14.0
    - torch==2.8.0
    - tqdm==4.67.1
    - triton==3.4.0
    - typing-extensions==4.15.0
    - tzdata==2025.2
    - urllib3==2.5.0
    - zarr==2.18.2
    - zipp==3.23.0
